In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
df = pd.read_parquet('../outputs/df_links5.parquet')
df

,title,score,n_links,n_comments,comments,thread_urls,first_link_utc,last_link_utc,url,description,...,reccomendations,disrecommendations,why,if_you_liked_x_you_will_like_this,rating_quality,rating_rationality,rating_writing,rating_plot,rating_character,rating_worldbuilding
0,Worth the Candle,5458,296,296,[{'author_flair_text': 'Self-Appointed Court S...,[https://reddit.com/r/rational/comments/7228po...,2015-09-26 06:59:23,2024-04-17 19:03:01,[https://archiveofourown.org/works/11478249/ch...,"Worth the Candle is a long, original, complete...",...,Readers frequently praised the story's compell...,Some readers found the sheer length of the wor...,Readers of r/rational would likely enjoy Worth...,"[Mother of Learning, HPMOR, Worm, Erfworld, Lu...",9.0,7.0,8.5,8.5,8.0,9.0
1,Mother of Learning,1834,174,174,"[{'author_flair_text': 'Utopian Smut Peddler',...",[https://reddit.com/r/rational/comments/k8i7jg...,2014-07-26 08:21:12,2024-05-21 07:04:42,[https://www.fictionpress.com/s/2961893/1/Moth...,Mother of Learning is a web serial about Zoria...,...,"Readers praise its consistent internal logic, ...",Some readers find the writing style to be roug...,Readers of r/rational will appreciate the stor...,"[Time Braid, HPMOR, Worm]",9.0,7.5,7.0,9.0,8.5,9.0
2,"Alexander Wales - The Metropolitan Man, Shadow...",1408,22,22,[{'author_flair_text': 'Time flies like an arr...,[https://reddit.com/r/rational/comments/galt0r...,2015-04-18 18:13:47,2021-04-29 20:00:04,[https://www.patreon.com/alexanderwales],"Alexander Wales's works, including *Shadows of...",...,Readers strongly recommend Alexander Wales's w...,Some readers express concerns about the infreq...,Readers of r/rational would likely enjoy Alexa...,"[Brandon Sanderson, Harry Potter, Worm, Mother...",9.0,7.5,9.0,9.0,8.5,8.0
3,A Practical Guide to Evil,1321,143,143,[{'author_flair_text': 'Ankh-Morpork City Watc...,[https://reddit.com/r/rational/comments/ako900...,2016-04-05 18:53:21,2024-08-09 10:10:21,"[https://practicalguidetoevil.wordpress.com/, ...",A Practical Guide to Evil is a long-running we...,...,"Readers praise its well-developed characters, ...",Some readers find the frequent cliffhangers ir...,Readers of r/rational will likely enjoy this f...,"[Worm, Shadows of the Limelight]",9.5,7.0,8.0,9.0,9.0,9.0
4,Worm,1019,96,96,[{'author_flair_text': 'Emergency Mustelid Hol...,[https://reddit.com/r/rational/comments/k8i7jg...,2014-01-27 02:09:42,2024-11-22 21:39:11,"[https://parahumans.wordpress.com/, https://pa...","Worm is a long, complete web serial (1.7 milli...",...,Readers recommend Worm for its compelling char...,"Some find the story too grim, dark, and depres...",Readers of r/rational might enjoy Worm for its...,"[HPMOR, A Practical Guide to Evil, Other Wildb...",9.0,7.0,8.5,8.5,8.0,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13218,"Worth the Candle, Chapter 121-122",-6,2,2,"[{'author_flair_text': None, 'body': 'It seems...",[https://reddit.com/r/rational/comments/9h1454...,2018-09-19 02:26:27,2018-09-19 04:51:09,[https://youtu.be/xq1tN9jZI80],In this chapter of the web serial *Worth the C...,...,"Readers praise the writing quality, emotional ...",Some readers find the emotional intensity and ...,Readers of r/rational might appreciate the foc...,[],7.5,8.0,8.5,8.0,7.0,9.0
13219,Heartbreaker,-6,1,1,[{'author_flair_text': 'https://i.imgur.com/OQ...,[https://reddit.com/r/rational/comments/48akta...,2016-02-29 20:57:08,2016-02-29 20:57:08,[https://parahumans.wordpress.com/2012/01/17/b...,Heartbreaker is mentioned only once in the pro...,...,No positive recommendations are given for Hear...,The comment referencing Heartbreaker is widely...,Heartbreaker is only mentioned in passing as a...,[],1.0,0.0,0.0,0.0,0.0,0.0
13220,Orthogonality Thesis Discussion Summary,-8,2,2,"[{'author_flair_text': None, 'body': 'I don't ...",[https://reddit.com/r/rational/comments/3vc0si...,2015-12-04 18:17:07,2016-07-11 16:27:30,[https://wiki.lesswrong.com/wiki/Orthogonality...,"The Orthogonality Thesis, a concept from LessW...",...,Users found the discussions engaging for their...,Some users found the discussions overly theore...,"Readers interested in AI alignment, rationalit...","[Discussions on Friendly AI, Sequences by Elie...",6.0,9.0,0.0,0.0,7.0,0.0
13221,"When Starting School, Younger Children Are Mor...",-9,1,1,[{'author_flair_text': 'Ankh-Morpork City Watc...,[https://reddit.com/r/rational/comments/a1t6um...,2018-11-30 17:17:49,2018-11-30 17:17:49,[https://news.harvard.edu/gazette/story/2018/1...,This Harvard Gazette article discusses a study...,...,The article's mention generated a discussion a...,"The article itself isn't fiction, generating d...",The discussion touches upon themes relevant to...,[],0.0,0.0,0.0,0.0,0.0,0.0
13222,Is There A Replicability Crisis In Psychology?...,-9,1,1,[{'author_flair_text': 'Ankh-Morpork City Watc...,[https://reddit.com/r/rational/comments/a1t6um...,2018-11-30 17:17:49,2018-11-30 17:17:49,[https://sciencetrends.com/is-there-a-replicab...,A Reddit user mentions a science article explo...,...,No recommendations are given for the article i...,"The article itself isn't fiction, and its ment...",Readers interested in the philosophy of scienc...,[],0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
# custom search
masks = [
    'score > 1',
    'rating_character > 1',
    'rating_plot > 1',
    'rating_rationality > 1',
]

print('Total: n=', len(df))
for m in masks:
    df = df.query(m)
    print(f'Filtered: n={len(df)} from `{m}`')

Total: n= 13223
Filtered: n=11549 from `score > 1`
Filtered: n=8811 from `rating_character > 1`
Filtered: n=8557 from `rating_plot > 1`
Filtered: n=8506 from `rating_rationality > 1`

In [4]:
df

,title,score,n_links,n_comments,comments,thread_urls,first_link_utc,last_link_utc,url,description,...,reccomendations,disrecommendations,why,if_you_liked_x_you_will_like_this,rating_quality,rating_rationality,rating_writing,rating_plot,rating_character,rating_worldbuilding
0,Worth the Candle,5458,296,296,[{'author_flair_text': 'Self-Appointed Court S...,[https://reddit.com/r/rational/comments/7228po...,2015-09-26 06:59:23,2024-04-17 19:03:01,[https://archiveofourown.org/works/11478249/ch...,"Worth the Candle is a long, original, complete...",...,Readers frequently praised the story's compell...,Some readers found the sheer length of the wor...,Readers of r/rational would likely enjoy Worth...,"[Mother of Learning, HPMOR, Worm, Erfworld, Lu...",9.0,7.0,8.5,8.5,8.0,9.0
1,Mother of Learning,1834,174,174,"[{'author_flair_text': 'Utopian Smut Peddler',...",[https://reddit.com/r/rational/comments/k8i7jg...,2014-07-26 08:21:12,2024-05-21 07:04:42,[https://www.fictionpress.com/s/2961893/1/Moth...,Mother of Learning is a web serial about Zoria...,...,"Readers praise its consistent internal logic, ...",Some readers find the writing style to be roug...,Readers of r/rational will appreciate the stor...,"[Time Braid, HPMOR, Worm]",9.0,7.5,7.0,9.0,8.5,9.0
2,"Alexander Wales - The Metropolitan Man, Shadow...",1408,22,22,[{'author_flair_text': 'Time flies like an arr...,[https://reddit.com/r/rational/comments/galt0r...,2015-04-18 18:13:47,2021-04-29 20:00:04,[https://www.patreon.com/alexanderwales],"Alexander Wales's works, including *Shadows of...",...,Readers strongly recommend Alexander Wales's w...,Some readers express concerns about the infreq...,Readers of r/rational would likely enjoy Alexa...,"[Brandon Sanderson, Harry Potter, Worm, Mother...",9.0,7.5,9.0,9.0,8.5,8.0
3,A Practical Guide to Evil,1321,143,143,[{'author_flair_text': 'Ankh-Morpork City Watc...,[https://reddit.com/r/rational/comments/ako900...,2016-04-05 18:53:21,2024-08-09 10:10:21,"[https://practicalguidetoevil.wordpress.com/, ...",A Practical Guide to Evil is a long-running we...,...,"Readers praise its well-developed characters, ...",Some readers find the frequent cliffhangers ir...,Readers of r/rational will likely enjoy this f...,"[Worm, Shadows of the Limelight]",9.5,7.0,8.0,9.0,9.0,9.0
4,Worm,1019,96,96,[{'author_flair_text': 'Emergency Mustelid Hol...,[https://reddit.com/r/rational/comments/k8i7jg...,2014-01-27 02:09:42,2024-11-22 21:39:11,"[https://parahumans.wordpress.com/, https://pa...","Worm is a long, complete web serial (1.7 milli...",...,Readers recommend Worm for its compelling char...,"Some find the story too grim, dark, and depres...",Readers of r/rational might enjoy Worm for its...,"[HPMOR, A Practical Guide to Evil, Other Wildb...",9.0,7.0,8.5,8.5,8.0,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11537,Schild's Ladder,2,1,1,"[{'author_flair_text': None, 'body': 'One of G...",[https://reddit.com/r/rational/comments/khj3a6...,2020-12-22 00:53:17,2020-12-22 00:53:17,[https://www.goodreads.com/book/show/156780.Sc...,Schild's Ladder is a long-form science fiction...,...,Readers recommend Schild's Ladder for its expl...,No specific negative reviews found in the data.,"Readers interested in hard sci-fi, transhumani...",[],7.5,8.0,7.0,7.0,7.0,8.0
11539,Karkadinn,2,1,1,[{'author_flair_text': 'My arch-enemy is entro...,[https://reddit.com/r/rational/comments/3zkruy...,2016-01-07 22:26:38,2016-01-07 22:26:38,[https://www.fanfiction.net/u/1092271/Karkadinn],Karkadinn is a fanfiction author known for wor...,...,Readers praise Karkadinn's stories for their b...,Some stories are incomplete or no longer being...,Readers of r/rational might enjoy Karkadinn's ...,[],8.2,7.0,8.0,8.5,8.0,7.5
11544,Inevitable,2,1,1,"[{'author_flair_text': 'seer of seers, prognos...",[https://reddit.com/r/rational/comments/biqik4...,2019-04-29 18:19:39,2019-04-29 18:19:39,[https://forums.spacebattles.com/threads/wormv...,Inevitable is a Worm oneshot fanfiction where ...,...,Readers recommend Inevitable for its in-depth ...,Some readers find the revised ending unsatisfa...,Readers of r/rational interested in Worm fanfi...,[Worm],8.5,9.0,8.0,8.0,7.0,9.0
11545,Just an Assistant,2,1,1,"[{'author_flair_text': None, 'body': 'For fict...",[https://reddit.com/r/rational/comments/ktpyd9...,2021-01-11 15:40:09,2021-01-11 15:40:09,[https://www.fimfiction.net/story/224797/just-...,"In this My Little Pony fanfic, Princess Luna a...",...,Readers recommend this fanfic for its interest...,Some readers find the topic of slavery inheren...,"Readers interested in morally gray characters,...",[Works exploring the justifications of slavery...,7.5,8.0,8.0,6.0,7.0,7.0
11548,"Humanity Fuck Yeah Thread (The Second, The Sec...",2,1,1,"[{'author_flair_text': None, 'body': 'I endors...",[https://reddit.com/r/rational/comments/23uwyc...,2014-04-25 20:07:05,2014-04-25 20:07:05,[http://forums.spacebattles.com/threads/humani...,This entry summarizes comments from r/rational...,...,The fic is praised by comparison to another wo...,No direct negative feedback on the main thread...,Readers might enjoy this if they are looking f...,"[Overlord game, Zero no Tsukaima, Worm (but le...",7.0,6.0,8.0,6.0,7.0,6.0

In [21]:
# old royalroaddl
df_rr = df[df['url'].apply(lambda x: any(['royalroad.com' in y for y in x]))]
df_rr = df_rr.query('first_link_utc < 2023')
df_rr

,title,score,n_links,n_comments,comments,thread_urls,first_link_utc,last_link_utc,url,description,...,reccomendations,disrecommendations,why,if_you_liked_x_you_will_like_this,rating_quality,rating_rationality,rating_writing,rating_plot,rating_character,rating_worldbuilding
0,Worth the Candle,5458,296,296,[{'author_flair_text': 'Self-Appointed Court S...,[https://reddit.com/r/rational/comments/7228po...,2015-09-26 06:59:23,2024-04-17 19:03:01,[https://archiveofourown.org/works/11478249/ch...,"Worth the Candle is a long, original, complete...",...,Readers frequently praised the story's compell...,Some readers found the sheer length of the wor...,Readers of r/rational would likely enjoy Worth...,"[Mother of Learning, HPMOR, Worm, Erfworld, Lu...",9.0,7.0,8.5,8.5,8.0,9.0
1,Mother of Learning,1834,174,174,"[{'author_flair_text': 'Utopian Smut Peddler',...",[https://reddit.com/r/rational/comments/k8i7jg...,2014-07-26 08:21:12,2024-05-21 07:04:42,[https://www.fictionpress.com/s/2961893/1/Moth...,Mother of Learning is a web serial about Zoria...,...,"Readers praise its consistent internal logic, ...",Some readers find the writing style to be roug...,Readers of r/rational will appreciate the stor...,"[Time Braid, HPMOR, Worm]",9.0,7.5,7.0,9.0,8.5,9.0
16,Delve,441,39,39,"[{'author_flair_text': None, 'body': 'Can I ju...",[https://reddit.com/r/rational/comments/giq6yv...,2019-07-05 15:23:19,2024-07-29 16:14:14,[https://www.royalroad.com/fiction/25225/delve...,Delve is a LitRPG isekai web serial where the ...,...,Readers who enjoy LitRPGs with a strong emphas...,"Many readers find the pacing incredibly slow, ...",Readers of r/rational might enjoy Delve for it...,"[Progression Fantasy, LitRPG with meaningful m...",6.0,7.0,5.0,6.0,6.0,7.0
18,Only Villains Do That,428,20,20,"[{'author_flair_text': 'Path to Victory', 'bod...",[https://reddit.com/r/rational/comments/mu17nk...,2021-04-19 16:42:21,2024-09-09 18:18:36,[https://www.royalroad.com/fiction/40182/only-...,Only Villains Do That is a web serial that fol...,...,Readers praise the story's subversion of iseka...,Some readers find the protagonist's misanthrop...,Readers of r/rational might enjoy Only Villain...,"[The Gods are Bastards, Worth the Candle, Over...",7.8,6.0,8.5,7.0,7.5,8.0
23,Ar'Kendrithyst,404,31,31,"[{'author_flair_text': None, 'body': 'I think ...",[https://reddit.com/r/rational/comments/mao94s...,2020-01-13 22:21:34,2024-11-18 15:07:29,[https://www.royalroad.com/fiction/26727/arken...,LitRPG isekai featuring a middle-aged pacifist...,...,Readers praise the well-developed world and in...,"Early chapters feature a naive, impulsive prot...",Readers of r/rational might enjoy Ar'Kendrithy...,"[Delve, Mother of Learning, System Apocalypse]",7.5,7.0,8.0,6.0,7.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11110,Synergy,2,1,1,"[{'author_flair_text': None, 'body': 'Some stu...",[https://reddit.com/r/rational/comments/kls3ju...,2021-01-04 15:33:08,2021-01-04 15:33:08,[https://www.royalroad.com/fiction/35374/synergy],Synergy is a LitRPG web serial on RoyalRoad. T...,...,Readers appreciated the focus on the importanc...,Some readers found the premise unremarkable or...,Readers of r/Rational might enjoy Synergy if t...,[To Play With Magic],7.0,6.0,6.5,6.5,6.0,6.0
11205,The Acts of Androkles,2,1,1,"[{'author_flair_text': None, 'body': 'I love t...",[https://reddit.com/r/rational/comments/e8b2i2...,2019-12-14 23:52:34,2019-12-14 23:52:34,[https://www.royalroad.com/fiction/25012/the-a...,The Acts of Androkles is a RoyalRoad web seria...,...,The story's immersive quality and engaging wri...,Some readers found the initial chapters to hav...,Readers looking for a well-written and engagin...,[],8.0,6.0,7.0,7.5,7.0,7.0
11229,Polyrhythm Time -- A Bard's Tail,2,2,2,"[{'author_flair_text': None, 'body': ' [https:...",[https://reddit.com/r/rational/comments/humufy...,2020-05-21 01:25:02,2020-07-27 12:55:28,[https://www.royalroad.com/fiction/30483/polyr...,Polyrhythm Time is a web serial that deconstru...,...,Readers recommend Polyrhythm Time for its uniq...,No significant negative reviews found in the p...,Readers of r/rational might enjoy Polyrhythm T...,[Peak (nonfiction book on expertise)],7.5,6.0,7.0,7.0,7.0,6.0
11428,It's Only Another End of the World,2,1,1,"[{'author_flair_text': None, 'body': 'There's ...",[https://reddit.com/r/rational/comments/je3ans...,2020-10-20 21:39:31,2020-10-20 21:39:31,[https://www.royalroad.com/fiction/20453/its-o...,It's only another end of the world is a Lovecr...,...,Readers recommended it for its Lovecraftian el...,No specific negative reviews were mentioned.,Readers interested in Lovecraftian cosmic horr...,"[Lovecraftian stories, Cosmic horror]",7.0,4.0,6.0,7.0,6.0,6.0
11483,Royaroad Dungeon Tag Fiction Summary,2,1,1,"[{'author_flair_text': None, 'body': 'You're n...",[https://reddit.com/r/rational/comments/cyq4ku...,2019-09-03 21:17:30,2019-09-03 21:17:30,[https://www.royalroad.com/fictions/search?tag...,This entry summarizes community recommendation...,...,Readers recommend stories for their engaging p...,Several stories are criticized for poor charac...,"Readers seeking progression fantasy, litRPG, o...","[Worm, Island in the Sea of Time, Destroyermen...",6.5,5.0,6.5,6.0,6.0,7.0

In [22]:
df_rr.tags

0        [web serial, LitRPG, isekai, portal fantasy, o...
1        [web serial, original fiction, fantasy, time l...
16       [Web Serial, LitRPG, Isekai, Fantasy, Progress...
18       [web serial, isekai, dark fantasy, political i...
23       [web serial, isekai, litrpg, fantasy, progress...
                               ...
11110    [web serial, LitRPG, isekai, progression fanta...
11205        [web serial, fantasy, well-written, engaging]
11229    [web serial, fantasy, progression, deconstruct...
11428    [web serial, complete, scifi, horror, Lovecraf...
11483    [web serial, litrpg, progression fantasy, isek...
Name: tags, Length: 479, dtype: object

In [23]:
d=df_rr
c='tags'
is_list = d[c].apply(lambda x: isinstance(x, list)).all()
is_list
x = d[c].iloc[0]
import numpy as np
isinstance(x, (list, tuple, np.ndarray))

True

In [29]:
df_rr.columns

Index(['title', 'score', 'n_links', 'n_comments', 'comments', 'thread_urls',
       'first_link_utc', 'last_link_utc', 'url', 'description', 'tags',
       'reviews_quotes', 'reviews_summary', 'reccomendations',
       'disrecommendations', 'why', 'if_you_liked_x_you_will_like_this',
       'rating_quality', 'rating_rationality', 'rating_writing', 'rating_plot',
       'rating_character', 'rating_worldbuilding'],
      dtype='object')

In [68]:
# put the long text columns last
# 1. get str columns
str_cols = df_rr.select_dtypes(include='object').columns
# exclude title, tags
str_cols = str_cols.difference(['title',])
# 2. get max length of each column
max_len = df_rr[str_cols].apply(lambda x: x.str.len().max())
# 3. sort by max length
max_len = max_len.sort_values(ascending=False)

# now sort the columns, with original order except for the ones in max_len
cols = list(df_rr.columns)
for c in max_len.index:
    cols.remove(c)
cols = cols + list(max_len.index)
df_rr = df_rr[cols]

In [69]:
from rrational.export import export_df_2_html
from pathlib import Path
from rrational.transform import join_uniq, chain_lists, format_flair, c2md, collapsibe, urls2a,url2a,  unique_elements, auto_transform_to_html

df_rr2 = auto_transform_to_html(df_rr.copy().drop(columns=['comments']))

export_df_2_html(df=df_rr2, output=Path('../outputs/df_links5.html'))

title, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

score, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

n_links, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

n_comments, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

first_link_utc, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

last_link_utc, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

rating_quality, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

rating_rationality, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

rating_writing, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

rating_plot, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

rating_character, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

rating_worldbuilding, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

description, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

tags, is_list=True, is_list_str=True, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

disrecommendations, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

reviews_summary, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

why, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

reccomendations, is_list=False, is_list_str=False, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

thread_urls, is_list=True, is_list_str=True, is_list_url=True, is_url=False, is_urls=False, is_list_obj=False

url, is_list=True, is_list_str=True, is_list_url=True, is_url=False, is_urls=False, is_list_obj=False

reviews_quotes, is_list=True, is_list_str=True, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False

if_you_liked_x_you_will_like_this, is_list=True, is_list_str=True, is_list_url=False, is_url=False, is_urls=False, is_list_obj=False